[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
test = "test"
script = "script"
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 100
via_ir = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]

remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "forge-std/=dependencies/forge-std-1.9.7/src/",
]

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.2.0"

[soldeer]
remappings_generate = false
remappings_regenerate = false

[rpc_endpoints]
robinhood_testnet = "${ROBINHOOD_TESTNET_RPC}"
robinhood = "${ROBINHOOD_RPC}"

[etherscan]
robinhood_testnet = { key = "${BLOCKSCOUT_API_KEY}", url = "${ROBINHOOD_TESTNET_BLOCKSCOUT_API}", chain = 46630 }
robinhood = { key = "${BLOCKSCOUT_API_KEY}", url = "${ROBINHOOD_BLOCKSCOUT_API}", chain = 4663 }

[lint]
exclude_lints = ["unsafe-typecast", "mixed-case-variable", "mixed-case-function", "pascal-case-struct"]
